# Generated by Django 3.1.4 on 2021-01-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_all_people', models.CharField(max_length=45, verbose_name='Имя')),
                ('age_all_people', models.IntegerField(verbose_name='Возраст')),
                ('phone_all_people', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('address_all_people', models.CharField(max_length=45, verbose_name='Адрес')),
                ('work_all_people', models.CharField(max_length=45, verbose_name='Место работы')),
                ('family_all_people', models.SmallIntegerField(verbose_name='В семье ... человек')),
                ('property_all_people', models.CharField(max_length=45, verbose_name='Имущество')),
                ('salary_all_people', models.IntegerField(verbose_name='Зарплата')),
            ],
            options={
                'verbose_name': 'Все люди',
                'verbose_name_plural': 'Все люди',
            },
        ),
        migrations.CreateModel(
            name='gibdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_gibdd', models.CharField(max_length=45, verbose_name='Имя')),
                ('shtrav_gibdd', models.CharField(max_length=45, verbose_name='Штраф')),
                ('phone_gibdd', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('address_gibdd', models.CharField(max_length=45, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Гибдд',
                'verbose_name_plural': 'Гибдд',
            },
        ),
        migrations.CreateModel(
            name='nalogovaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_nalogovaja', models.CharField(max_length=45, verbose_name='Имя')),
                ('property_nalogovaja', models.CharField(max_length=45, verbose_name='Имущество')),
                ('dolg_nalogovaja', models.IntegerField(verbose_name='Долг')),
            ],
            options={
                'verbose_name': 'Налоговая',
                'verbose_name_plural': 'Налоговая',
            },
        ),
        migrations.CreateModel(
            name='pasportnij_stol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pasportnij_stol', models.CharField(max_length=45, verbose_name='Имя')),
                ('serija_nomer_pasportnij_stol', models.CharField(max_length=45, verbose_name='Серия и нмоер паспорта')),
                ('data_vidachi_pasportnij_stol', models.DateField(verbose_name='Дата выдачи')),
            ],
            options={
                'verbose_name': 'Паспортный стол',
                'verbose_name_plural': 'Паспортный стол',
            },
        ),
        migrations.CreateModel(
            name='pensionnij_fond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pensionnij_fond', models.CharField(max_length=45, verbose_name='Имя')),
                ('salary_pensionnij_fond', models.IntegerField(verbose_name='Зарплата')),
            ],
            options={
                'verbose_name': 'Пенсионный фонд',
                'verbose_name_plural': 'Пенсионный фонд',
            },
        ),
        migrations.CreateModel(
            name='slujba_zaniatosti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_slujba_zaniatosti', models.CharField(max_length=45, verbose_name='Имя')),
                ('work_slujba_zaniatosti', models.CharField(max_length=20, verbose_name='Место работы')),
            ],
            options={
                'verbose_name': 'Служба занятости',
                'verbose_name_plural': 'Служба занятости',
            },
        ),
        migrations.CreateModel(
            name='zags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ZAGS', models.CharField(max_length=45, verbose_name='Имя')),
                ('family_ZAGS', models.IntegerField(verbose_name='Членов семьи')),
            ],
            options={
                'verbose_name': 'ЗАГС',
                'verbose_name_plural': 'ЗАГС',
            },
        ),
    ]
