# Generated by Django 3.1.4 on 2021-01-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naselenije', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPeople',
            fields=[
                ('idall_people', models.AutoField(primary_key=True, serialize=False)),
                ('name_all_people', models.CharField(max_length=45)),
                ('age_all_people', models.IntegerField(blank=True, null=True)),
                ('address_all_people', models.CharField(blank=True, max_length=45, null=True)),
                ('phone_all_people', models.CharField(blank=True, max_length=20, null=True)),
                ('work_all_people', models.CharField(blank=True, max_length=45, null=True)),
                ('family_all_people', models.IntegerField(blank=True, null=True)),
                ('property_all_people', models.CharField(blank=True, max_length=45, null=True)),
                ('salary_all_people', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'all_people',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasportnijStol',
            fields=[
                ('idpasportnij_stol', models.IntegerField(primary_key=True, serialize=False)),
                ('name_pasportnij_stol', models.CharField(blank=True, max_length=45, null=True)),
                ('serija_nomer_pasportnij_stol', models.CharField(blank=True, max_length=45, null=True)),
                ('data_vidachi_pasportnij_stol', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pasportnij_stol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PensionnijFond',
            fields=[
                ('idpensionnij_fond', models.IntegerField(primary_key=True, serialize=False)),
                ('name_pensionnij_fond', models.CharField(blank=True, max_length=45, null=True)),
                ('salary_pensionnij_fond', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pensionnij_fond',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SlujbaZaniatosti',
            fields=[
                ('idslujba_zaniatosti', models.IntegerField(primary_key=True, serialize=False)),
                ('name_slujba_zaniatosti', models.CharField(blank=True, max_length=45, null=True)),
                ('work_slujba_zaniatosti', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'slujba_zaniatosti',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='all_people',
        ),
        migrations.DeleteModel(
            name='pasportnij_stol',
        ),
        migrations.DeleteModel(
            name='pensionnij_fond',
        ),
        migrations.DeleteModel(
            name='slujba_zaniatosti',
        ),
        migrations.AlterModelOptions(
            name='gibdd',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='nalogovaja',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='zags',
            options={'managed': False},
        ),
    ]
